create database ola_database;
use ola_database;
show tables;
select * from bengaluru_ola_booking_data;
describe bengaluru_ola_booking_data;
-- CHANGING DATATYPES --
update bengaluru_ola_booking_data
set Date = replace(Date,'/','-');
update bengaluru_ola_booking_data
set Date = str_to_date(Date, '%m-%d-%Y');
alter table bengaluru_ola_booking_data
modify column Date date;
alter table bengaluru_ola_booking_data
modify column Time time;
alter table bengaluru_ola_booking_data
modify column `Booking ID` VARCHAR(10);
alter table bengaluru_ola_booking_data
modify column `Booking Status` Varchar(25);
alter table bengaluru_ola_booking_data
modify `Customer ID` int;
alter table bengaluru_ola_booking_data
modify `Vehicle Type` varchar(20);
alter table bengaluru_ola_booking_data
modify `Pickup Location` varchar(8);
alter table bengaluru_ola_booking_data
modify `Drop Location` varchar(8);
alter table bengaluru_ola_booking_data
modify `Avg VTAT` time;
alter table bengaluru_ola_booking_data
modify `Avg CTAT` time;
alter table bengaluru_ola_booking_data
modify `Cancelled Rides by Customer` int;
alter table bengaluru_ola_booking_data
modify `Reason for Cancelling by Customer` varchar(50);
alter table bengaluru_ola_booking_data
modify `Cancelled Rides by Driver` int;
alter table bengaluru_ola_booking_data
modify `Reason for Cancelling by Driver` varchar(50);
alter table bengaluru_ola_booking_data
modify `Incomplete Rides` int;
alter table bengaluru_ola_booking_data
modify `Incomplete Rides Reason` varchar(50);
alter table bengaluru_ola_booking_data
modify `Booking Value` float;
alter table bengaluru_ola_booking_data
modify `Payment Method` varchar(10);
alter table bengaluru_ola_booking_data
modify `Ride Distance` float;
alter table bengaluru_ola_booking_data
modify `Driver Ratings` float;
alter table bengaluru_ola_booking_data
modify `Customer Rating` float;

-- Q1] TOP 25 CUSTOMERS WHO HAVE COMPLETED MOST BOOKINGS --
SELECT `Customer ID`,
COUNT(`Booking ID`) AS `Total Rides`,
SUM(`Booking Value`) AS `Total Amount`
FROM bengaluru_ola_booking_data
GROUP BY `Customer ID`
ORDER BY `Total Rides` DESC 
LIMIT 25;

-- Q2] DRIVERS WHO RECIEVED RATINGS BELOW 3.0 --     
select `Booking ID`,`Customer ID`
from bengaluru_ola_booking_data
where `Driver Ratings` < 3.0;
       
-- Q3] TOP 5 DRIVERS WHO COMPLETED LONGEST DIST TRIPS --
SELECT `Booking ID`, 
MAX(`Ride Distance`) AS `Longest Trip Distance`
FROM bengaluru_ola_booking_data
WHERE `Booking Status` = 'Completed'
GROUP BY `Booking ID`
ORDER BY `Longest Trip Distance` DESC
LIMIT 5;

-- Q4] AVERAGE RIDE DIST FOR EACH VEHICLE TYPE --
SELECT `Vehicle Type`,
AVG(`Ride Distance`) As `Average Ride Diatance` 
FROM bengaluru_ola_booking_data
GROUP BY `Vehicle Type`;

-- Q5] AVERAGE CUSTOMER RATINGS PER VEHICLE TYPE --
SELECT `Vehicle Type`, 
AVG(`Customer Rating`) AS `Avg Customer Ratings` 
FROM bengaluru_ola_booking_data 
GROUP BY `Vehicle Type`;

-- Q6] REVENUE GENERATED FROM PRIME SEDAN VS PRIME SUV --
SELECT `Vehicle Type`,
SUM(`Booking Value`) AS `Prime Sedan Revenue`
FROM bengaluru_ola_booking_data
WHERE `Vehicle Type` = 'Prime Sedan';

SELECT `Vehicle Type`,
SUM(`Booking Value`) AS `Prime SUV Revenue`
FROM bengaluru_ola_booking_data
WHERE `Vehicle Type` = 'Prime SUV';

-- Q7] BUSIEST DAYS AS PER BOOKINGS
SELECT 
DAYNAME(`Date`) AS `Day of Week`,
COUNT(*) AS `Total Bookings`
FROM bengaluru_ola_booking_data
GROUP BY DAYNAME(`Date`)
ORDER BY `Total Bookings` DESC
LIMIT 10;

-- Q8]  TOP 3 MOST TRAVELLED ROUTES BASED ON PICKUP LOCATION & DROP LOCATION --
SELECT `Pickup Location`,`Drop Location`,
COUNT(*) AS `Total Trips`
FROM bengaluru_ola_booking_data
GROUP BY `Pickup Location`, `Drop Location`
ORDER BY `Total Trips` DESC
LIMIT 3;

-- Q9] TOP MOST CANCELLATION REASONS BY CUSTOMER
SELECT `Reason for Cancelling by Customer`,
COUNT(*) AS `Total Cancellations`
FROM bengaluru_ola_booking_data
WHERE `Reason for Cancelling by Customer` IS NOT NULL
GROUP BY `Reason for Cancelling by Customer`
ORDER BY `Total Cancellations`
Limit 2;
 
-- INSIGHTS--
-- NO.1 More peoples are preferring auto, mini & bike because they charge less fair as compared to others for intercity travel 
-- NO.2 In premium car class revenue generated by Prime sedan is higher as compared to prime suv so company should invest more in prime sedan segment 
-- NO.3 Monday,Tuesday,Friday,Wednesday & Thursday are the busiest booking days as compared to saturday and sunday company should avail more cabs on these days
-- NO.4 Most travelled routes are Area 7,8,9,36,43,44 on these routes more cabs should be available
-- NO.5 Most cancellation reasons by customers are because of Wrong Address & Driver asked to cancel so company should take this two reasons into consideration to reduce cancellation rate 




